---
name: Arch Linux command runner
description: Runs a command in an Arch Linux container

branding:
  icon: terminal
  color: green

inputs:
  command:
    description: Command to run
    required: true
runs:
  using: docker
  image: Dockerfile
