name: Test

on:
  - push
  - pull_request

jobs:
  test:
    name: Test

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache
        uses: actions/cache@v2
        timeout-minutes: 1
        continue-on-error: true
        with:
          path: |
            ~/work/_temp/_github_home/.cargo/registry
            ~/work/_temp/_github_home/.cargo/git
            target
          key: ${{ github.job }}-${{ hashFiles('rust-toolchain.toml') }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ github.job }}-${{ hashFiles('rust-toolchain.toml') }}-${{ hashFiles('**/Cargo.lock') }}
            ${{ github.job }}-${{ hashFiles('rust-toolchain.toml') }}-

      - name: Build
        uses: ./ci/github-actions/arch-run
        with:
          command: cargo build --locked

      - name: Test
        uses: ./ci/github-actions/arch-run
        with:
          command: cargo test

      - name: Clippy
        uses: ./ci/github-actions/arch-run
        with:
          command: cargo clippy -- -D warnings

      - name: Enable reading of cache
        continue-on-error: true
        uses: ./ci/github-actions/arch-run
        with:
          command: chmod -R a+rwX $HOME/.cargo target

  fmt_check:
    name: Fmt

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1.0.7
        with:
          profile: minimal
          components: rustfmt
          override: 'true'
          default: 'true'
          toolchain: 'rust-toolchain.toml'

      - name: Check code formatting
        run: cargo fmt -- --check
